version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: storypoint
      POSTGRES_PASSWORD: storypoint
      POSTGRES_DB: storypoint
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
volumes:
  db-data:
